# Generated by Django 4.2.7 on 2023-11-15 05:34

from django.db import migrations, models
import myapi.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default=myapi.models.generate_unique_code, max_length=8, unique=True),
        ),
    ]
